# Generated by Django 3.2.18 on 2023-07-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'start_time', 'end_time')},
        ),
    ]
