# Generated by Django 3.2.18 on 2023-06-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='booked',
            new_name='in_person',
        ),
        migrations.AddField(
            model_name='appointment',
            name='virtual',
            field=models.BooleanField(default=False),
        ),
    ]
