# Generated by Django 3.2.18 on 2023-06-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='month',
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
