# Generated by Django 3.2.18 on 2023-04-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_counsel'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counsel',
            name='attended_to',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counsel',
            name='dept',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
