# Generated by Django 3.2.18 on 2023-06-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230605_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
