# Generated by Django 3.2.18 on 2023-06-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
