# Generated by Django 3.2.18 on 2023-06-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230608_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='in_person',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='virtual',
        ),
        migrations.RemoveField(
            model_name='article',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='appointment',
            name='session_type',
            field=models.CharField(blank=True, choices=[('in_person', 'In Person'), ('virtual', 'Virtual')], max_length=15, null=True, verbose_name='Select your preferred counselling type:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
