# Generated by Django 3.2.18 on 2023-04-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230424_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='subtitle',
        ),
    ]
