# Generated by Django 3.2.18 on 2023-06-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230615_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='session_type',
            field=models.CharField(blank=True, choices=[('in_person', 'In Person'), ('virtual', 'Virtual')], max_length=15, null=True),
        ),
    ]
