# Generated by Django 3.2.18 on 2023-06-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_appointment_session_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='type',
        ),
    ]
