# Generated by Django 3.2.18 on 2023-06-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='session_type',
            field=models.CharField(blank=True, choices=[('in_person', 'In Person'), ('virtual', 'Virtual')], max_length=15, null=True, verbose_name='Select your preferred counselling type'),
        ),
    ]
